"""Added fulfilled to supplyorder

Revision ID: 7e9b9d57b191
Revises: d266b8818a99
Create Date: 2024-06-27 15:49:19.423153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e9b9d57b191'
down_revision = 'd266b8818a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SupplyOrder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fulfilled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SupplyOrder', schema=None) as batch_op:
        batch_op.drop_column('fulfilled')

    # ### end Alembic commands ###
