"""Initial migration

Revision ID: 88a0acbb1dc9
Revises: 
Create Date: 2024-06-26 13:50:16.562275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a0acbb1dc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_type', sa.String(length=1), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('blue', sa.Integer(), nullable=True),
    sa.Column('red', sa.Integer(), nullable=True),
    sa.Column('grey', sa.Integer(), nullable=True),
    sa.Column('accountmanager_checked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SupplyOrder',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('blue', sa.Integer(), nullable=False),
    sa.Column('red', sa.Integer(), nullable=False),
    sa.Column('grey', sa.Integer(), nullable=False),
    sa.Column('incorrect_delivery', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('OrderId', sa.Integer(), nullable=True),
    sa.Column('SupplyOrderId', sa.Integer(), nullable=True),
    sa.Column('date_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('activity', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['OrderId'], ['Order.id'], ),
    sa.ForeignKeyConstraint(['SupplyOrderId'], ['SupplyOrder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Record')
    op.drop_table('SupplyOrder')
    op.drop_table('Order')
    # ### end Alembic commands ###
