"""Add stock class

Revision ID: ca0f79010a13
Revises: df4e49b178e5
Create Date: 2024-06-27 11:06:33.725001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca0f79010a13'
down_revision = 'df4e49b178e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Stock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('blue', sa.Integer(), nullable=False),
    sa.Column('red', sa.Integer(), nullable=False),
    sa.Column('grey', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Stock')
    # ### end Alembic commands ###
