"""changed correct delivery supply order

Revision ID: d266b8818a99
Revises: ca0f79010a13
Create Date: 2024-06-27 15:06:20.648937

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd266b8818a99'
down_revision = 'ca0f79010a13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SupplyOrder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_delivery', sa.Boolean(), nullable=True))
        batch_op.drop_column('incorrect_delivery')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SupplyOrder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incorrect_delivery', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('correct_delivery')

    # ### end Alembic commands ###
